# https://docs.gitlab.com/runner/executors/docker.html
# This file is a template, and might need editing before it works on your project.
# Official images to be found on https://hub.docker.com/u/library/?page=2
# For instance:
# - https://hub.docker.com/_/java/ - Official Java image
# - https://hub.docker.com/_/centos/ - Official CentOS image
image: library/centos:7
#image: java:7

before_script:
  # Update the system
  - yum -y update
  # Install SBT
  - curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
  - rpm --import "http://dl.bintray.com/sbt/rpm/repodata/:repomd.xml.key"
  - yum -y install sbt
  # Log the sbt version
  - sbt sbt-version

test:
  script:
    # Execute the test
    #- sbt clean test
    - sbt compile

